{
    # --------- GENERAL PARAMETERS ---------

    "experiment_name": "demo_exp",  # experiment name
    "latent_inference_model": "uniform",
    "cuda": true,  
    "seed": 1,  # -1 for random seed
    "verbose": true,

    # --------- DATA SETTINGS ---------

    "target_image_root": "data/set47_bsd",  # path to data folder
    "degraded_image_root": null,

    "n_bits": 8,
    "n_samples": 3,  # number of images to restore. -1 to restore all dataset images

    # --------- INVERSE PROBLEM SETTINGS ---------

    "problem": "sisr",  # deblur, sisr, inpainting or denoising
    "sigma": 0,  # std of a white Gaussian noise for the inverse problems in [0,255]

    # deblurring parameters
    "kernel": null, # access to a blur kernel .npy format
    "kernel_std": null,  # Gaussian noise std, overwritten by kernel if kernel is not None
    "kernel_size": null,  # Size of the Gaussian kernel, overwritten by kernel if kernel is not None

    # single image super resolution paramters
    "scale_factor": 4,  # scale factor for SISR

    # inpainting pameters
    "mask": null,  # access to an inpainting mask .npy format
    "proba_missing": null,  # missing pixels probability, overwritten by mask if mask is not None

    # --------- MODEL LOADING ---------

    "model": null,  # path to model checkpoint
    "model_type": null,  # CAE models: 'mbt', 'cheng'

    # --------- REGULARIZATION PARAMETERS ---------

    "lamb": 2.3,  # Regularization param in L(z) = ||AD(z) - y ||² + lambda R(z)
    "save_all_estimates": true,  # True to save all estimates for VBLE algo (in particular, z and a to do additional posterior sampling)

    # --------- OPTIMIZATION PARAMETERS ---------

    "lr": 0.1,  # learning rate
    "max_iters": 300,  # number of iterations
    "datafit_loss_type": "ll",
    "optimizer_name": "adam",  # adam or sgd
    "n_samples_sgvb": 1,  # Number of samples for computing the SGVB estimate at each iteration. If instability during VBLE optimization, increase this number
    "posterior_sampling_batch_size": 4,  # batch size for posterior sampling
}